Wining/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from Wining import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("search/", include("search.urls")),
    path("detail/", include("detail.urls")),
    path("user/", include("user.urls")),
    path("board/", include("board.urls")),
    path("store/", include("store.urls")),
    path("purchasing/", include("purchasing.urls")),
    path("errorhandling/", include("errorhandling.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
from django.urls.conf import path
from board import views


from django.conf import settings
from django.conf.urls.static import static

app_name = "board"

urlpatterns = [  # init_url == "http://localhost:8000/board/list"
    path("list", views.ListView.as_view(), name="list"),
    path("list/", views.ListView.as_view(), name="board_list"),
    path("write", views.WriteView.as_view(), name="write"),
    path(
        "deletecomment/<int:comment_id>/",
        views.DeleteCommentView.as_view(),
        name="deletecomment",
    ),
    path("writecomment/", views.WriteCommentView.as_view(), name="writecomment"),
    path("content", views.ContentView.as_view(), name="content"),
    path("content/<int:board_id>/", views.ContentView.as_view(), name="content"),
    #    path("content/", views.ContentView.as_view(), name="content"),
    #    path("contentpro", views.ContentProView.as_view(), name="contentpro"),
    path("delete", views.DeleteView.as_view(), name="delete"),
    path("update", views.UpdateView.as_view(), name="update"),
    path("updatepro", views.UpdateProView.as_view(), name="updatepro"),
    path("board/content/", views.ContentView.as_view(), name="content"),
    # path('board/toggle_like/', views.ContentView.as_view().toggle_like, name='toggle_like'),
    #    path("content/", views.ContentView.as_view(), name="content"),
    #    path("contentpro", views.ContentProView.as_view(), name="contentpro"),
    #    path("image", views.ImageView.as_view(), name="image"),
    #    path("imagedown", views.ImageDownView.as_view(), name="imagedown"),
    path("uploadimage", views.UploadImageView.as_view(), name="uploadimage"),
	path('updatecomment/', views.UpdateCommentView.as_view(), name="updatecomment") 
]
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_URL
)  # MEDIA 경로 추가
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # MEDIA 경로 추가

user/urls.py
from django.urls.conf import path
from user import views

urlpatterns = [  # init_url == "http://localhost:8000/user/login"
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("inputUser", views.InputUserView.as_view(), name="inputUser"),
    path("inputStore", views.InputStoreView.as_view(), name="inputStore"),
    path("confirmId", views.ConfirmIdView.as_view(), name="confirmId"),
    path("delete", views.DeleteView.as_view(), name="delete"),
    path("myPage", views.MyPageView.as_view(), name="myPage"),
    path("modifyUser", views.ModifyUserView.as_view(), name="modifyUser"),
    path("reviewWrite", views.ReviewWriteView.as_view(), name="reviewWrite"),
    path("reviewList", views.ReviewListView.as_view(), name="reviewList"),
    path("purchaseDetail", views.PurchaseDetailView.as_view(), name="purchaseDetail"),
    path("myBoard", views.MyBoardView.as_view(), name="myBoard"),
    path("addPoint", views.AddPointView.as_view(), name="addPoint"),
    path("addPointHis", views.AddPointHisView.as_view(), name="addPointHis"),
    path("myComment", views.MyCommentView.as_view(), name="myComment"),
]

board/models.py
from django.db import models

# from .models import Post


class WinBoard(models.Model):
    board_id = models.AutoField(primary_key=True)
    user = models.ForeignKey("user.WinUser", models.CASCADE)  #
    board_title = models.CharField(max_length=150)
    board_reg_time = models.DateTimeField()
    board_content = models.TextField()
    board_read_count = models.IntegerField()
    board_ip = models.CharField(max_length=20)

    class Meta:
        #    managed = False
        db_table = "win_board"


class WinBoardImg(models.Model):
    board_img_id = models.AutoField(primary_key=True)
    board = models.ForeignKey(WinBoard, models.CASCADE)  #
    board_image = models.ImageField(max_length=150)

    class Meta:
        #   managed = False
        db_table = "win_board_img"


class WinComment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    board = models.ForeignKey(WinBoard, models.CASCADE)
    user = models.ForeignKey("user.WinUser", models.CASCADE)  #
    comment_content = models.ImageField(max_length=500)
    comment_reg_time = models.DateTimeField()
    content_ip = models.CharField(max_length=20)

    class Meta:
        #    managed = False
        db_table = "win_comment"


class WinBoardLike(models.Model):
    board_like_id = models.AutoField(primary_key=True)
    user = models.ForeignKey("user.WinUser", models.CASCADE)
    board = models.ForeignKey(WinBoard, models.CASCADE)
    board_like_time = models.DateTimeField()

    class Meta:
        # managed = False
        db_table = "win_board_like"

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.views.generic.base import View
from django.http.response import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from board.models import WinBoard, WinBoardImg, WinComment
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.utils.dateformat import DateFormat
from _datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count

PAGE_SIZE = 20  # 한페이지에 표시할 게시물 개수
PAGE_BLOCK = 5  # 페이지 블록의 크기


# ListView는 게시판 페이지네이션과 게시글 목록을 구성하기 위해 필요한 데이터 계산
class ListView(View):
    def get(self, request):
        template = loader.get_template("board/list.html")
        count = WinBoard.objects.all().count()  # Board 모델이 저장된 게시글의 총 개수
        if count == 0:  # 게시글이 없는 경우
            context = {  # 템플릿에서도 사용하도록 변수 count 추가
                "count": count,
            }
        else:  # 게시글이 있는 경우
            pagenum = request.GET.get("pagenum")  # pagenum(현재 페이지 번호) 가져옴
            if not pagenum:  # pagenum(현재페이지번호)이 존재하지 않는 경우,
                pagenum = "1"  # 그때의 값을 1이라고 하자.
            pagenum = int(pagenum)  # pagenum:현재페이지번호     pagesize:페이지당 글개수
            start = (pagenum - 1) * int(PAGE_SIZE)  # (5-1)*10 + 1 = 41
            end = start + int(PAGE_SIZE)  # 41 + 10 - 1 = 50
            if end > count:  # end(끝인덱스)가 게시글 총 개수를 초과한다면...
                end = count  # end를 게시글 총개수로 바꾼다.

            search_query = request.GET.get("q")  # 검색어 가져오기
            if search_query:
                dtos = (
                    WinBoard.objects.annotate(comment_count=Count("wincomment"))
                    .filter(board_title__icontains=search_query)
                    .order_by("-board_reg_time")[start:end]
                )
                count = dtos.count()
            else:
                dtos = WinBoard.objects.annotate(
                    comment_count=Count("wincomment")
                ).order_by("-board_reg_time")[start:end]

            number = count - (pagenum - 1) * int(PAGE_SIZE)
            number = number - count - 1
            abs(number)

            startpage = pagenum // int(PAGE_BLOCK) * int(PAGE_BLOCK) + 1
            if pagenum % int(PAGE_BLOCK) == 0:
                startpage -= PAGE_BLOCK
            endpage = startpage + int(PAGE_BLOCK) - 1
            # startpage와 endpage를 계산하여 페이징 처리를 위한 페이지 번호의 범위를 구한다.

            pagecount = count // int(PAGE_SIZE)  # pagecount:총페이지 수

            if count % int(PAGE_SIZE) > 0:
                pagecount += 1
            if endpage > pagecount:  # endpage가 pagecount를 초과한다면
                endpage = pagecount  # endpage를 pagecount로 설정한다.
            pages = range(startpage, endpage + 1)

            context = {  # 필요한 변수들을 context내부에 추가해서 템플릿에서 사용할 수 있도록 한다.
                "count": count,
                "pagenum": pagenum,
                "dtos": dtos,
                "number": number,
                "startpage": startpage,
                "endpage": endpage,
                "pages": pages,
                "pageblock": PAGE_BLOCK,
                "pagecount": pagecount,
                "search_query": search_query,
                # "comment_count" : comment_count,
            }
        return HttpResponse(template.render(context, request))
        # 템플릿 렌더링한 결과를 context를 사용해서 Httpresponse로 return한다.


from django.core.files.storage import default_storage
from django.conf import settings


# 게시글 작성 기능담당. get요청-> 작성폼 보여줌   /  post요청-> 작성된 게시글 저장
class WriteView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):  # dispatch메서드
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):  # get메서드
        template = loader.get_template("board/write.html")  # 해당 템플릿 로드
        num = request.GET.get("num")  # MultiValueDictKeyError 방지
        user_id = request.session.get("memid")
        # num :게시글번호
        # 템플릿에 전달한 변수를 context에 작성
        context = {
            "num": num,
            "user_id": user_id,
        }
        return HttpResponse(template.render(context, request))

    # post메서드
    def post(self, request):
        # user_id = request.POST.get("writer")
        board_title = request.POST.get("subject")
        board_content = request.POST.get("content")
        board_image = request.FILES.get("img")

        if not board_title or not board_content:
            # 필수 입력 필드가 누락된 경우 처리
            template = loader.get_template("board/write.html")
            context = {
                "num": request.POST.get("num"),
                "message": "모든 필드를 입력해주세요.",
            }
            return HttpResponse(template.render(context, request))

        dto = WinBoard(
            user_id=request.session.get("memid"),
            board_title=board_title,
            board_content=board_content,
            board_read_count=0,
            board_reg_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            board_ip=request.META.get("REMOTE_ADDR"),
            #board_like=0,
            # board_image=image_url,
        )
        dto.save()  # 생성된 객체를 DB에 저장

        if board_image:
            # 이미지가 업로드된 경우
            # 이미지를 파일로 저장
            image_path = default_storage.save("images/" + board_image.name, board_image)
            # 저장된 파일의 경로
            # image_url = settings.MEDIA_URL + image_path                                 # /media/images/
            image_url = "/" + image_path
            # WinBoardImg 모델에 저장
            win_board_img = WinBoardImg(board=dto, board_image=image_url)
            win_board_img.save()
        return redirect("board:list")  # boardlist url로 돌아감


class WriteCommentView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        template = loader.get_template("board/writecomment.html")
        num = request.GET.get("board_id")  # MultiValueDictKeyError 방지
        user_id = request.session.get("memid")
        context = {
            "num": num,
            "user_id": user_id,
        }

        return HttpResponse(template.render(context, request))

    def post(self, request):
        board_id = request.POST.get("board_id")
        user_id = request.POST.get("writer")
        comment_content = request.POST.get("content")

        if not comment_content:
            # 필수 입력 필드가 누락된 경우 처리
            template = loader.get_template("board/writecomment.html")
            context = {
                "num": board_id,
                "message": "모든 필드를 입력해주세요.",
            }
            return HttpResponse(template.render(context, request))

        dtc = WinComment(
            # comment_id=request.POST["commenter"],
            board_id=board_id,
            user_id=user_id,
            comment_content=comment_content,
            comment_reg_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            content_ip=request.META.get("REMOTE_ADDR"),
        )
        dtc.save()

        return redirect("board:list")  # 리디렉션할 URL로 수정

@method_decorator(csrf_exempt, name='dispatch')
class UpdateCommentView(View):
    def post(self, request):
        comment_id = request.POST.get("comment_id")  # 수정할 댓글의 ID
        comment_content = request.POST.get("comment_content")  # 수정된 댓글 내용
        
        # 댓글 ID와 내용이 모두 넘어왔는지 확인
        if not comment_id or not comment_content:
            return JsonResponse({"success": False, "message": "모든 필드를 입력해주세요."})
        
        try:
            # DB에서 해당 댓글 가져오기
            comment = WinComment.objects.get(id=comment_id)
        except WinComment.DoesNotExist:
            return JsonResponse({"success": False, "message": "해당 댓글을 찾을 수 없습니다."})
        
        # 댓글 내용 업데이트
        comment.comment_content = comment_content
        comment.save()
        
        # 수정된 댓글 내용을 응답으로 보내기
        return JsonResponse({
            "success": True,
            "comment_id": comment.id,
            "comment_content": comment.comment_content,
            "comment_reg_time": comment.comment_reg_time.strftime("%Y-%m-%d %H:%M:%S"),
            "user_id": comment.user_id,
        })

class DeleteCommentView(View):
    def delete(self, request, comment_id=None):
        dtc = get_object_or_404(WinComment, comment_id=comment_id)
        dtc.board_id = request.GET.get("board_id")
        pagenum = request.GET.get("pagenum")

        dtc.delete()

        return JsonResponse({"success": True})

    def post(self, request, comment_id=None):
        dtc = get_object_or_404(WinComment, comment_id=comment_id)
        dtc.board_id = request.POST.get("board_id")
        pagenum = request.POST.get("pagenum")

        dtc.delete()

        return JsonResponse({"success": True})


from django.utils import timezone
import json


class ContentView(View):
    def get(self, request):
        template = loader.get_template("board/content.html")
        num = request.GET.get("num")
        pagenum = request.GET.get("pagenum")
        number = request.GET.get("number")

        # 필수 매개변수가 없는 경우 기본값 설정
        if not num:
            num = 0
        else:
            num = int(num)

        dto = get_object_or_404(WinBoard, board_id=num)

        if dto.board_ip != request.META.get("REMOTE_ADDR"):
            dto.board_read_count += 1
            dto.save()

        dtcs = WinComment.objects.filter(board_id=num).values(
            "comment_id",
            "board_id",
            "user_id",
            "comment_content",
            "comment_reg_time",
            "content_ip",
        )


templates/board/deletecomment.html
<html>
<h3>댓글 삭제</h3>
<p>댓글을 삭제하시겠습니까?</p>
<p>{{ dtc.comment_content }}</p>
	<form method="post" action="{% url 'board:deletecomment' %}">
	  {% csrf_token %}
	  <input type="hidden" name="comment_id" value="{{ dtc.comment_id }}">
	  <input type="submit" value="확인">
	  <a href="{% url 'board:content' dtc.board.board_id %}?pagenum={{ pagenum }}">취소</a>
	</form>

</html>

templates/board/list.html
{% extends "board/base.html" %}
{% load mathfilters %}
{% load static %}

{% block title %}
  <h2>자유 게시판 ( 총 : {{ count }}개 )</h2>
{% endblock %}

{% block content %}
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<button class="btn btn-primary scroll-button top-button" onclick="scrollToTop()"><i class="fas fa-arrow-up"></i> </button>
<button class="btn btn-primary scroll-button bottom-button" onclick="scrollToBottom()"><i class="fas fa-arrow-down"></i></button>






	<div class="container my-3">
	  <div class="row">
	    <div class="col-lg-6 mb-3">
	      <form class="d-flex" method="get" action="{% url 'board:list' %}">
	        <input class="form-control me-2" type="search" name="q" placeholder="검색어를 입력하세요" style="width:900px;">
	        <button class="btn btn-outline-primary" type="submit" style="width:150px;">검색</button>
	      </form>
	    </div>
	    	{% if request.session.memid  %}
			    <div class="col-lg-6 mb-3 text-end">
			      <a href="{% url 'board:write' %}" class="btn btn-outline-primary">글쓰기</a>
			    </div>
	  		{% endif %}
	  </div>

  <!-- 검색 결과 표시 -->
  {% if search_query %}
    <h3>검색 결과 : <span style="color:red;">"{{ search_query }}"</span> 에 해당하는 글이 <span style="color:red;">{{count}} </span>개 있습니다.</h3>
  {% endif %}


	
    
    
    <br>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr class="table-dark">
            <th style="width: 7%; text-align:center;">글번호</th>
            <th style="width: 40%">제목</th>
            <th style="width: 10%; text-align:center;">작성자</th>
            <th style="width: 15%; text-align:center;">작성일</th>
            <th style="width: 8%; text-align:center;">조회수</th>
          </tr>
        </thead>
        <tbody>
          {% if count == 0 %}
            <tr>
              <td colspan="5" align="center">
               	"{{search_query}}" 에 해당하는 글이 없습니다.
              </td>
            </tr>
          {% else %}
            {% for dto in dtos %}
              <tr>
                <td align="center">
                	{{ number|sub:forloop.counter0|abs }}</td>
                <td>
                  {% if dto.board_read_count != -1 %}
                    <a href="content?num={{ dto.board_id }}&pagenum={{ pagenum }}&number={{ number|sub:forloop.counter0|abs }}" >
                      {{ dto.board_title }}
                      <span class="comment-count" style="color:blue;"> ({{ dto.comment_count }})</span>
                    </a>
                  {% else %}
                    삭제된 글입니다.
                  {% endif %}
                </td>
                <td align="center" style="color:cadetblue;">
                  {% if dto.board_read_count == -1 %}
                    &nbsp;
                  {% else %}
                    {{ dto.user_id }}
                  {% endif %}
                </td>
                <td align="center">
                  {% if dto.board_read_count == -1 %}
                    &nbsp;
                  {% else %}
                    {{ dto.board_reg_time|date:"Y-m-d H:i:s" }}
                  {% endif %}
                </td>
                <td align="center">
                  {% if dto.board_read_count == -1 %}
                    &nbsp;
                  {% else %}
                    {{ dto.board_read_count }}
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>	
</div>






    <div class="pagination justify-content-center">
      {% if startpage > pageblock %}
        <a href="{% url 'board:list' %}?pagenum={{ startpage|sub:pageblock }}">&laquo;</a>
      {% endif %}

      {% for i in pages %}
        {% if i == pagenum %}
          <span class="current-page">{{ i }}</span>
        {% else %}
          <a href="{% url 'board:list' %}?pagenum={{ i }}">{{ i }}</a>
        {% endif %}
      {% endfor %}

      {% if pagecount > endpage %}
        <a href="list?pagenum={{ startpage|add:pageblock }}" class="page-link">&raquo;</a>
      {% endif %}
    </div><br><br>
    
    
	<script>
		function scrollToTop() {
		  window.scrollTo(0, 0);
		}
	
		function scrollToBottom() {
		  window.scrollTo(0, document.body.scrollHeight);
		}
	</script>

  <style>
  .scroll-button {
    position: fixed;
    padding: 5px;
    font-size: 18px;
    border: none;
    background-color: transparent;
    cursor: pointer;
    color:grey;
  }

  .top-button {
    bottom: 60px;
    right: 20px;
  }

  .bottom-button {
    bottom: 20px;
    right: 20px;
  }
  
  
  
  
  
  	.title-text {
  		color: pink;
  	}
  
  
    .pagination {
      margin-top: 20px;
    }

    .pagination a,
    .pagination span {
      display: inline-block;
      margin: 5px;
      padding: 5px 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      text-decoration: none;
      color: #333;
    }

    .pagination a:hover {
      background-color: #f0f0f0;
    }

    .pagination .current-page {
      background-color: #007bff;
      color: #fff;
      border-color: #007bff;
    }
  </style>
{% endblock %}

templates/board/searched.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 mb-3">
      <form class="d-flex" method="get" action="{% url 'board:list' %}">
        <input class="form-control me-2" type="search" name="q" placeholder="검색어를 입력하세요" style="width:900px;">
        <button class="btn btn-outline-primary" type="submit" style="width:150px;">검색</button>
      </form>
    </div>
    <div class="col-lg-6 mb-3 text-end">
      <a href="{% url 'board:write' %}" class="btn btn-outline-primary">글쓰기</a>
    </div>
  </div>

  <h1>검색 결과</h1>

{% if query %}
    <h3>검색어: {{ query }}</h3>
  {% endif %}

  {% if posts %}
    <ul>
      {% for post in posts %}
        <li>{{ post.title }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>검색 결과가 없습니다.</p>
  {% endif %}

{% endblock %}

templates/board/write.html
{% extends "board/base.html" %}

{% block title %}<h2>글 쓰기</h2>{% endblock %}


{% block content %}
<div class="container">
	<form method="post" action="{% url 'board:write' %}" name="writeform" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="hidden" name="num" value="{{ num }}">

		<div class="mb-3">
			<a href="{% url 'board:list' %}" class="btn btn-secondary">글 목록</a>
		</div>
			
			<div class="mb-3">
				<label for="writer" class="form-label">작성자</label>
				<input class="form-control" type="text" name="writer" id="writer" value="{{ user_id }}" maxlength="50" readonly>
			</div>
			
		<div class="mb-3">
			<label for="subject" class="form-label">제목</label>
			<input class="form-control" type="text" name="subject" id="subject" maxlength="300" autofocus>
		</div>
		<div class="mb-3">
			<label for="content" class="form-label">내용</label>
			<textarea class="form-control" name="content" id="content" rows="10" cols="40"></textarea>
		</div>
		<div class="mb-3">
			<div class="col-lg-6">
				<div class="form-group">
					<label for="img" class="form-label">이미지</label>
					<input class="form-control" type="file" name="img" id="img" accept="image/*">
				</div>
			</div>
		</div>
		
		<!--  
		<div class="mb-3">
			<label for="passwd" class="form-label">비밀번호</label>
			<input class="form-control" type="password" name="passwd" id="passwd" maxlength="50">
		</div>
		-->
		<br>
		<div class="mb-3 d-flex justify-content-center">
			<input class="btn btn-primary" type="submit" value="작성" >&nbsp;
			<input class="btn btn-secondary" type="reset" value="취소" autofocus>&nbsp;
			<input class="btn btn-secondary" type="button" value="뒤로가기" onclick="history.go(-1)">
		</div>

	</form>
</div>
{% endblock %}

 
<script>













	document.querySelector("form[name='writeform']").addEventListener("submit", function(event) {
		event.preventDefault(); // 폼 제출 이벤트를 중지

		//var writer = document.getElementById("writer").value;
		var subject = document.getElementById("subject").value;
		var content = document.getElementById("content").value;
		//var passwd = document.getElementById("passwd").value;
		/*
		if (writer.trim() === '' || subject.trim() === '' || content.trim() === '' || passwd.trim() === '') {
			return false; // 모든 필드가 입력되지 않았을 경우 함수 종료
		}
		*/
		if (subject.trim() === '' || content.trim() === '') {
			return false; // 모든 필드가 입력되지 않았을 경우 함수 종료
		}
		
		// 폼 데이터를 서버로 전송하는 AJAX 요청
		var formData = new FormData(this);
		var xhr = new XMLHttpRequest();
		xhr.open("POST", "write", true);
		xhr.onreadystatechange = function() {
			if (xhr.readyState === 4 && xhr.status === 200) {
				// 요청이 성공적으로 완료되었을 때 처리할 로직
				console.log(xhr.responseText); // 응답 데이터 출력 (예시)
				showSuccessAlert();
			}
		};
		xhr.send(formData);
	});

	
	
	
	function showSuccessAlert() {
		var alertDiv = document.createElement("div");
		alertDiv.classList.add("alert", "alert-success", "mt-3", "position-fixed", "top-0", "start-50", "translate-middle-x");
		alertDiv.innerText = "글이 작성되었습니다.";
		document.body.appendChild(alertDiv);
		
		setTimeout(function() {
			alertDiv.style.display = "none";
			location.href =  "{% url 'board:content' num %}";
		}, 3000);
	}
</script>

 

templates/board/writecomment.html
{% extends "board/base.html" %}

{% block title %}<h2> 댓글 쓰기</h2>{% endblock %}


{% block content %}
<div class="container">
	<form method="post" action="{% url 'board:writecomment' %}" name="writecommentform">
	{% csrf_token %}
		<!--  <input type="hidden" name="num" value="{{ num }}">-->
		<input type="hidden" name="board_id" value="{{num}}">

		<div class="mb-3">
			<a href="{% url 'board:list' %}" class="btn btn-secondary">글 목록</a>
		</div>
		{% if request.session.memid %}
			<div class="mb-3">
				<label for="writer" class="form-label">작성자</label>
				<input class="form-control" type="text" name="writer" id="writer" maxlength="50" value="{{ user_id }}" readonly>
			</div>
		{% endif %}
		<div class="mb-3">
			<label for="content" class="form-label">내용</label>
			<textarea class="form-control" name="content" id="content" rows="10" cols="40" autofocus></textarea>
		</div>

		<div class="mb-3">
			<input class="btn btn-primary" type="submit" value="작성">
			<input class="btn btn-secondary" type="reset" value="취소" autofocus>
			<input class="btn btn-secondary" type="button" value="작성취소" onclick="history.go(-1)">
		</div>

	</form>
</div>
{% endblock %}